# Generated by Django 4.1.4 on 2023-01-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='home_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='visitors_point',
            field=models.IntegerField(default=0),
        ),
    ]
