# Generated by Django 4.1.4 on 2023-01-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_remove_game_id_game_season_alter_game_game_id_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='fgp',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stats',
            name='ftp',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stats',
            name='min',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stats',
            name='tpp',
            field=models.CharField(max_length=10),
        ),
    ]
