# Generated by Django 4.1.4 on 2023-02-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_alter_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='home_point',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='visitors_point',
            field=models.IntegerField(),
        ),
    ]
