# Generated by Django 4.1.4 on 2023-02-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_alter_game_home_point_alter_game_visitors_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='pos',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
